name: PR Continuos Integration

on: pull_request

jobs:
  pr-continuos-integration:
    runs-on: ubunto-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Install, Build & Testes
        run: |
          mvn clean install
          mvn test